import enum

class TrackedDevicesInfo(enum.StrEnum):
    COMPUTER = "computer"
    LENS_NAME = "Image focusing lens"
    LENS_MODEL = "AC254-080-A-ML"
    WHITE_RABBIT_DEVICE_NAME = "harp_clock_generator"
    DETECTOR_BIN_WIDTH = 4
    DETECTOR_BIN_HEIGHT = 4
    DETECTOR_MODEL = "BFS-U3-20S40M"
    DETECTOR_CROP_WIDTH = 200
    DETECTOR_CROP_HEIGHT = 200
    DETECTOR_BIT_DEPTH = 16
    PORT_COM = "COM14"
    PORT_CLOCK = "ClkOut"
    PATCH_CORD_MODEL = "BBP(4)_200/220/900-0.37_Custom_FCM-4xMF1.25"
    PATCH_CORD_DIAMETER = 200
    PATCH_CORD_NUMERICAL_APERTURE = 0.37